- repo: local
  hooks:
    - id: SwiftLint
      name: SwiftLint
      entry: bash -c 'PATH=/usr/local/bin:$PATH  mint run swiftlint --quiet --no-cache --strict'
      language: system
      pass_filenames: false

