default_platform(:ios)

platform :ios do
  desc "Run all tests"
  lane :run_all_tests do
    run_tests(scheme: "ComradeDVR")
    spm(package_path: "./src/AutocontainerKit", command: "test")
    # generate project due to UIKit usage
    spm(package_path: "./src/CameraKit", command: "generate-xcodeproj")
    run_tests(project: "./src/CameraKit/CameraKit.xcodeproj")
  end

  desc "Testflight build"
  lane :test_flight do
    gym(
      scheme: "ComradeDVR",
      clean: true,
      output_name: "ComradeDVR.ipa",
      configuration: "Production",
      export_options: {
        provisioningProfiles: {
          "com.trszdev.ComradeDVR": "ComradeDVR AppStore profile",
        },
      },
      sdk: "iphoneos14.5"
    )
  end
end
