devices([
  "iPhone 11",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (12.9-inch) (2nd generation)",
])

concurrent_simulators(false)
languages(["en-US", "ru-RU"])
scheme("ScreenshotTool")
output_directory("./screenshots")
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

