include:
  - ./config.production.yml
  - ./config.staging.yml
  - ./config.debug.yml

configs:
  Production: release
  Staging: release
  Debug: debug

options:
  usesTabs: false
  indentWidth: 2
  developmentLanguage: ru
  minimumXcodeGenVersion: 2.3.0
  deploymentTarget:
    iOS: 14.0
  defaultConfig: Production
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1 # iphone/ipod/ipad

