settings:
  configs:
    Staging:
      ENABLE_TESTABILITY: NO
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES

